CREATE TABLE if not exists users(Name varchar(32) not null, UserId varchar(15) not null, Password varchar(20) not null, PrevOrders varchar(25)); 

CREATE TABLE if not exists sandwich(Name varchar(25) not null, Time integer not null, Price float not null, Ingredients varchar array[10] not null, Bread varchar array[10] not null);

CREATE TABLE if not exists pizza_calzone(Name varchar(25) not null, Time integer not null, Price float not null, Ingredients varchar array[10] not null);

CREATE TABLE if not exists active_orders(UserName varchar(32) not null, Item varchar array[5] not null, PickupTime integer not null);

CREATE TABLE if not exists inventory(ingredientId varchar(25) not null, stockId BIT not null, primary key(ingredientId));

INSERT into sandwich values ('Baker Bacon', 7, 6.89, ['bacon', 'pepperjack', 'lettuce', 'tomato', 'balsamic vinaigrette'], ['white', 'wheat', 'ciabatta', 'potato rose', 'wholegrain']), ('BBQ Chicken', 7, 6.89, ['chicken', 'bacon', 'mozzarella', 'bbq sauce', 'lettuce', 'tomato', 'onion'], ['white', 'wheat', 'ciabatta', 'potato rose', 'wholegrain']), ('BLT', 7, 4.89, ['bacon', 'lettuce', 'tomato'], ['white', 'wheat', 'ciabatta', 'potato rose', 'whole grain']), ('Italian', 7, 6.89, ['pepperoni', 'salami', 'ham', 'provolone', 'lettuce', 'tomato', 'onion', 'italian dressing', 'salt and pepper'], ['white', 'wheat', 'ciabatta', 'potato rose', 'wholegrain']), ('Darley Divine', 7, 6.89, ['chicken', 'marinara', 'mozzarella', 'parmesan','spinach','tomato'], ['white', 'wheat', 'ciabatta', 'potato rose', 'whole grain']), ('Farrand Fodder', 7, 6.89, ['basil pesto', 'mozzarella', 'spinach', 'cucumber', 'tomato', 'hummus'], ['white', 'wheat', 'ciabatta', 'potato rose', 'wholegrain']), ('Hallet Ham', 7, 6.89, ['ham', 'cheddar', 'lettuce', 'tomato'], ['white', 'wheat', 'ciabatta', 'potato rose', 'whole grain']), ('Libby Licous', 7, 6.89, ['fontina', 'mozzarella', 'parmesan'], ['white', 'wheat', 'ciabatta', 'potato rose', 'whole grain']), ('Parmesan Grilled Cheese', 7, 5.89, ['fontina', 'balsamic onions', 'tomato'], ['white', 'wheat', 'ciabatta', 'potato rose', 'whole grain']), ('Tofu Mozzarella', 7, 5.89, ['tofu', 'mozzarella', 'lettuce', 'tomato', 'balsamic onions'], ['white', 'wheat', 'ciabatta', 'potato rose', 'whole grain']), ('Tuna Melt', 7, 5.89, ['tuna salad', 'swiss', 'lettuce', 'tomato', 'onion'], ['white', 'wheat', 'ciabatta', 'potato rose', 'whole grain']), ('Turkey Bacon Club', 7, 6.89, ['turkey', 'bacon', 'provolone', 'lettuce', 'tomato', 'onion']. ['white', 'wheat', 'ciabatta', 'potato rose', 'whole grain']), ('Turkey Jalapeno Melt', 7, 6.89, ['turkey', 'pepper jack', 'jalapeno', 'lettuce', 'tomato', 'onion'], ['white', 'wheat', 'ciabatta', 'potato rose', 'whole grain']), ('Veggie Club', 7,  6.89, ['spinach', 'bell peppers', 'mushrooms', 'cucumbers', 'lettuce', 'tomato','balsamic onions'], ['white', 'wheat', 'ciabatta', 'potato rose', 'wholegrain']);
 
INSERT into pizza_calzone values ('Cheese Pizza', 20, 4.89, ['Mozzarella', 'Red Sauce']),('Pepperoni Pizza', 20,5.49,['Mozzarella','Red Sauce','Pepperoni']),('BBQ Chicken Pizza',20,6.89,['Mozzarella','BBQ Sauce','Chicken','Bacon','Onion']),('Meat Lovers Pizza',20,6.98,['Mozzarella','Sausage','Ham','Pepperoni','Red Sauce']),('Hawaiian Pizza',20,6.89,['Mozzarella','Pineapple','Ham','Red Sauce']),('Margherita Pizza',20,5.49,['Mozzarella','Tomato','Basil','Garlic','Red Sauce']),('Vegetarian Pizza',20,5.49,['Mozzarella','Spinach','Bell Peppers','Mushrooms','Red Sauce']),('Vegan Pizza',20,5.39,['Tomato','Garlic','Black Olives','Basil','Red Sauce']),('Cheese Calzone', 20, 5.89, ['Mozzarella']),('Pepperoni Calzone', 20,6.49,['Mozzarella','Pepperoni']),('BBQ Chicken Calzone',20,7.89,['Mozzarella','BBQ Sauce Side','Chicken','Bacon','Onion']),('Meat Lovers Calzone',20,7.98,['Mozzarella','Sausage','Ham','Pepperoni']),('Hawaiian Calzone',20,7.89,['Mozzarella','Pineapple','Ham']),('Margherita Calzone',20,6.49,['Mozzarella','Tomato','Basil','Garlic']),('Vegetarian Calzone',20,6.49,['Mozzarella','Spinach','Bell Peppers','Mushrooms']),('Vegan Calzone',20,6.39,['Tomato','Garlic','Black Olives','Basil']);

INSERT into inventory values ('White Bread', 1), ('Wheat Bread', 1), ('Ciabatta', 1), ('Potato Rosemary', 1), ('Whole Grain', 1), ('Bacon', 1), ('Chicken', 1), ('Ham', 1), ('Salami', 1), ('Pepperoni', 1), ('Sausage', 1),('Turkey',1), ('Cheddar', 1), ('Mozzarella', 1), ('Provolone', 1), ('Pepper Jack', 1), ('Fontina', 1), ('Swiss', 1), ('Parmesan', 1),  ('Lettuce', 1), ('Tomato', 1), ('Spinach', 1), ('Onion',1),('Mushrooms',1),('Bell Peppers',1), ('Banana Peppers',1), ('Cucumbers',1), ('Balsamic Onions', 1),('Black Olives',1),('Jalapenos',1),('Pineapple', 1), ('BBQ Sauce', 1), ('Red Sauce', 1), ('Hummus', 1), ('Garlic', 1), ('Basil', 1);